### ISSUE TITLE
[Us 1] - Dream House in Colares

### ISSUE THREAD

**Issue by MarouAna** [MLops-NovaIms/SaveTheWorld-#1]
**Dream House in Colares**
Joao and Maria just moved to Portugal from Brazil and would like to buy a house in the Sintra area in Colares. They are thinking of a dwelling house, with a garden and pool near the forest. To take decisions and create the budget related to utilities such as buying air conditions, adding central heating, and using and recycling the rainwater, they asked the Mlpos NovaIms team to predict the future clime conditions in the area. To take decisions and answer the following questions:
• How many air conditions they will need? How powerful they should be?
• Do they need to add central heating?
• How much will rain in the next 5 years? Is the rain enough to be used for gardening and recycling the rainwater for the pool?

**Comment by MarouAna** [comment]
What about location? We pick lisbon?

**Comment by danielm09** [comment]
We can pick Serra da Estrela, central Portugal.

**Comment by danielm09** [comment]
What about the spatial unit (spatial resolution)?

**Comment by MarouAna** [comment]
Calores Sintra
[What about pick a forest or ](https://snirh.apambiente.pt/index.php?idRef=MTIyMw==&FILTRA_BACIA=138&FILTRA_COVER=920123704&FILTRA_SITE=920685202)

**Comment by MarouAna** [comment]
Add fire to predict?

**Comment by MarouAna** [comment]
**User Story**
Joao and Maria just moved to Portugal from Brazil and would like to buy a house in the Sintra area in Calores. They are thinking of a dwelling house, with a garden and pool near the forest. To take decisions and create the budget related to utilities such as buying air conditions, adding central heating, and using and recycling the rainwater, they asked the Mlpos NovaIms team to predict the future clime conditions in the area. To take decisions and answer the following questions: 
•	How many air conditions they will need? How powerful they should be? 
•	Do they need to add central heating? 
•	How much will rain in the next 5 years? Is the rain enough to be used for gardening and recycling the rainwater for the pool? 
•	What is the possibility of a fire in the area based on the temperature? Is it dangerous?

**Comment by JJ** [comment]
Can you please change the title to something a bit less generic?

**Comment by danielm09** [comment]
We checked the burned areas provided by ICNF and in the neighbourhood of the Colares station there were not fires reported since 1975. Therefore, we can eliminate the fire assessment from our analysis.

**Comment by MarouAna** [comment]
> Can you please change the title to something a bit less generic?

**Dream House in Calores**

**Comment by MarouAna** [comment]
> So, basically our objective is to model air temperature, right? To do that we are going to collect historical temperature data. But are going to use other variables (e.g. precipitation, amount of vegetation in the neighbourhood)?

We need temperature and precipitation data only.

**Comment by MarouAna** [comment]
> What about the spatial unit (spatial resolution)?

Not sure

**Comment by JJ** [comment]
It's probably better if you don't close this until you've finished a couple of milestones more...

**Comment by Rosa-Rafe** [comment]
For this story, we need the max and min temperature in the year and the precipitation average amount in the year.
Each year will be a vector
