### ISSUE TITLE
Download the data

### ISSUE THREAD

**Issue by Rosa-Rafe** [MLops-NovaIms/SaveTheWorld-#13]
#1 request to download the data
write a script for downloading data for two URLs that you have

**Comment by MASOTs** [comment]
Downloading data from worldclim

We tried perl with the following code:

# Module implementation here
use LWP::Simple;

use constant OSK_URL => 'https://biogeo.ucdavis.edu/data/worldclim/v2.1/hist/wc2.1_2.5m_tmax_2010-2018.zip';
my $data = get(OSK_URL) or die "Can't download " . OSK_URL;

print "We're good" if $data;

and then we use culr 

https://biogeo.ucdavis.edu/data/worldclim/v2.1/hist/wc2.1_2.5m_tmax_2010-2018.zip
