### ISSUE TITLE
Error on CURL

### ISSUE THREAD

**Issue by danielm09** [MLops-NovaIms/SaveTheWorld-#14]
"the underlying connection was closed could not establish secure channel for ssl/tls"

URL: https://snirh.pt/snirh/_dadosbase/site/paraCSV/dados_csv.php?sites=920685260&pars=1436794570,1520200094&tmin=01/10/1965&tmax=10/03/2022&formato=csv

**Comment by JJ** [comment]
This worked:

```
 curl --insecure https://snirh.pt/snirh/_dadosbase/site/paraCSV/dados_csv.php\?sites\=920685260\&pars\=1436794570,1520200094\&tmin\=01/10/1965\&tmax\=10/03/2022\&formato\=csv
```

Curl version:

```
curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1
```

**Comment by JJ** [comment]
In powershelgl you apparently can do it directly from the command line: https://stackoverflow.com/a/14223384/891440

**Comment by JJ** [comment]
And this one? https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.2

**Comment by MarouAna** [comment]
To download it with pure Powershell we just need to skip the certificate validation, as the site does not have a valid certificate for the name it is using,
Invoke-WebRequest -SkipCertificateCheck -Uri "https://snirh.pt/snirh/_dadosbase/site/paraCSV/dados_csv.php?sites=920685260&pars=1436794570,1520200094&tmin=01/10/1965&tmax=10/03/2022&formato=csv" -Outfile "dados.csv"

For the SkipCertificateCheck flag to be available Powershell 7 is required. It can be easily downloaded from the Microsoft Store. 
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-7.2
