### ISSUE TITLE
Find data sources for the project

### ISSUE THREAD

**Issue by JJ** [MLops-NovaIms/SaveTheWorld-#3]
Related to #1, find real data sources and write it down in a SOURCES.md file

**Comment by danielm09** [comment]
This link has some data about temperature and precipitation.

[http://portaldoclima.pt/pt/#]

**Comment by danielm09** [comment]
Link where you can find the burned areas in Portugal.
You need to type "ardido" in the filter and look for the "Territórios ardidos" dataset.

[https://geocatalogo.icnf.pt/catalogo.html](url)

**Comment by MASOTs** [comment]
https://snirh.pt/snirh/_dadosbase/site/simplex.php?OBJINFO=DADOS&FILTRA_BACIA=138&FILTRA_COVER=920123704&FILTRA_SITE=920685260

**Comment by Rosa-Rafe** [comment]
It seems good and we could choose the monthly average temperature and monthly precipitation value
