### ISSUE TITLE
Discussion: inherent characteristics of our data

### ISSUE THREAD

**Issue by danielm09** [MLops-NovaIms/SaveTheWorld-#34]
- Precipitation
Type of data: Numeric (float)
Range: 0 - 10,000 (???)
Change from instance to the next: ???
- Temperature
Type of data: Numeric (float)
Range: 0 - 100ºC (??)
Change from instance to the next: 20ºC (??)

**Comment by MarouAna** [comment]
Precipitation
    Type of data: Numeric (float)
    Range: 0 - 1000
    Change from instance to the next: ???
    Temperature
    Type of data: Numeric (float)
    Range: -40ºC - 70ºC 
    Change from instance to the next: 20ºC (??)

**Comment by MarouAna** [comment]
We are creating a standard to then text our data set based on that.

**Comment by MASOTs** [comment]
For precipitation, we can consider a variation between months of 500 mm, and for temperature monthly variation would be 50ºC

Precipitation
Monthly Variation: 500 mm
Temperature
Monthly Variation: 50ºC

**Comment by Rosa-Rafe** [comment]
for the range we have to put the unit for example mm.

**Comment by JJ** [comment]
> For precipitation, we can consider a variation between months of 500 mm, and for temperature monthly variation would be 50ºC
> 
> Precipitation Monthly Variation: 500 mm Temperature Monthly Variation: 50ºC

The data you have is monthly? Not daily?

**Comment by JJ** [comment]
Maybe link the data you are using so that we can see effectively what kind of ranges are there?
